import{calculate}from'./calculator.mjs';
const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);const pct=n=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:2}).format(n);let result,settings;
function render(){try{settings={amount:Number($('amount').value),rate:Number($('rate').value),tax:$('tax').value===''?NaN:Number($('tax').value),year:Number($('year').value),half:$('plan').value==='half'};result=calculate(settings);$('error').hidden=true;$('results').hidden=false;$('schedule').hidden=false;const r=result;$('saving').textContent=euro(r.saving);$('percentage').textContent=pct(r.saving/settings.amount*100)+'% dell’investimento';$('ordinary').textContent=euro(r.ordinarySaving);$('net').textContent=euro(r.net);$('total').textContent=euro(r.total);$('duration').textContent=`${r.rows.length} annualità · ${r.rows[0].year}–${r.rows.at(-1).year} · Risparmio aggiuntivo stimato, a capienza fiscale piena.`;
$('rows').innerHTML=r.rows.map(x=>`<tr><td>${x.year}</td>${[x.quota,x.deduction,x.ordinary,x.benefit,x.cumulative].map(v=>`<td>${euro(v)}</td>`).join('')}</tr>`).join('');$('totals').innerHTML=`<tr><td>Totale</td>${[settings.amount,r.extra,r.ordinarySaving,r.saving,r.saving].map(v=>`<td>${euro(v)}</td>`).join('')}</tr>`;
$('formula').textContent=`Extra deduzione: ${euro(r.extra)}. Risparmio aggiuntivo = extra deduzione × ${pct(settings.tax)}% = ${euro(r.saving)}. Recupero complessivo = ${euro(r.ordinarySaving)} ordinari + ${euro(r.saving)} di incentivo = ${euro(r.total)}.`;
const max=r.saving||1,W=760,H=250,l=76,b=215,top=20;const points=r.rows.map((x,i)=>[l+i*(W-l-20)/Math.max(1,r.rows.length-1),b-x.cumulative/max*(b-top)]);const line=points.map(p=>p.join(',')).join(' ');
$('chart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Recupero cumulato dell’incentivo da ${euro(r.rows[0].cumulative)} a ${euro(r.saving)}; valori annuali nella tabella"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#76b9ab" stop-opacity=".6"/><stop offset="100%" stop-color="#76b9ab" stop-opacity=".05"/></linearGradient></defs>${[0,.25,.5,.75,1].map(f=>`<line x1="${l}" x2="740" y1="${b-f*(b-top)}" y2="${b-f*(b-top)}" stroke="#dce2e7" stroke-dasharray="4 5"/><text x="65" y="${b-f*(b-top)+4}" text-anchor="end" font-size="11" fill="#607084">${pct(r.saving*f/1000)}k €</text>`).join('')}<polygon points="${l},${b} ${line} ${points.at(-1)[0]},${b}" fill="url(#fill)"/><polyline points="${line}" fill="none" stroke="#126b59" stroke-width="3"/>${points.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#126b59" stroke="white" stroke-width="2"><title>${r.rows[i].year}: ${euro(r.rows[i].cumulative)}</title></circle><text x="${p[0]}" y="240" text-anchor="middle" font-size="12" fill="#50617b">${r.rows[i].year}</text>`).join('')}</svg>`;
}catch(e){result=null;$('error').textContent=e.message;$('error').hidden=false;$('results').hidden=true;$('schedule').hidden=true;$('formula').textContent='Completa i dati per visualizzare la formula.'}}
$('form').addEventListener('input',render);$('form').addEventListener('submit',e=>e.preventDefault());$('print').addEventListener('click',()=>window.print());$('csv').addEventListener('click',()=>{if(!result)return;const num=n=>n.toFixed(2).replace('.',',');const lines=[['Calcolo incentivi - Simulazione iperammortamento 2026'],['Importo',num(settings.amount)],['Aliquota ammortamento',num(settings.rate)],['Aliquota fiscale',num(settings.tax)],['Piano',settings.half?'Primo anno al 50%':'Quote intere'],['Ipotesi','Capienza fiscale piena; unico investimento annualita; no IRAP o attualizzazione'],['Anno','Quota ordinaria','Extra deduzione','Risparmio ordinario','Risparmio incentivo','Cumulato incentivo'],...result.rows.map(r=>[r.year,...[r.quota,r.deduction,r.ordinary,r.benefit,r.cumulative].map(num)]),['Totale',...[settings.amount,result.extra,result.ordinarySaving,result.saving,result.saving].map(num)]];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='calcolo-incentivi-piano.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});render();
